[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[context.production.environment]
  NODE_ENV = "production"

  [build.environment]
  NODE_VERSION = "18.19.1"

